version: '3'

services:
  trojan-panel-caddy:
    image: caddy:2.6.2
    container_name: trojan-panel-caddy
    restart: always
    ports:
      - "${CADDY_HTTP_PORT:-80}:80"
      - "${CADDY_HTTPS_PORT:-443}:443"
    volumes:
      - "${TP_DATA:-/tpdata}/caddy/config.json:/tpdata/caddy/config.json"
      - "${TP_DATA:-/tpdata}/cert/:/tpdata/cert/certificates/acme-v02.api.letsencrypt.org-directory/${DOMAIN:-example.com}/"
      - "${TP_DATA:-/tpdata}/web/:/tpdata/web/"
      - "${TP_DATA:-/tpdata}/caddy/logs/:/tpdata/caddy/logs/"
    command: caddy run --config /tpdata/caddy/config.json

  trojan-panel-mariadb:
    image: mariadb:10.7.3
    container_name: trojan-panel-mariadb
    restart: always
    ports:
      - "${MARIADB_PORT:-9507}:9507"
    environment:
      MYSQL_DATABASE: trojan_panel_db
      MYSQL_ROOT_PASSWORD: "${MARIADB_PASSWORD:-changeme}"
      TZ: ${TZ:-Asia/Shanghai}
    volumes:
      - "${TP_DATA:-/tpdata}/mariadb:/var/lib/mysql"
    command: --port=9507

  trojan-panel-redis:
    image: redis:6.2.7
    container_name: trojan-panel-redis
    restart: always
    ports:
      - "${REDIS_PORT:-6378}:6378"
    volumes:
      - "${TP_DATA:-/tpdata}/redis:/data"
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme} --port 6378

  trojan-panel:
    image: jonssonyan/trojan-panel
    container_name: trojan-panel
    restart: always
    ports:
      - "${PANEL_PORT:-8081}:8081"
    volumes:
      - "${TP_DATA:-/tpdata}/web/:/tpdata/trojan-panel/webfile/"
      - "${TP_DATA:-/tpdata}/trojan-panel/logs/:/tpdata/trojan-panel/logs/"
      - "${TP_DATA:-/tpdata}/trojan-panel/config/:/tpdata/trojan-panel/config/"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=trojan-panel-mariadb"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${MARIADB_PASSWORD:-changeme}"
      - "redis_host=trojan-panel-redis"
      - "redis_port=6378"
      - "redis_pass=${REDIS_PASSWORD:-changeme}"
      - "server_port=8081"
    depends_on:
      - trojan-panel-mariadb
      - trojan-panel-redis

  trojan-panel-ui:
    image: jonssonyan/trojan-panel-ui
    container_name: trojan-panel-ui
    restart: always
    ports:
      - "${UI_PORT:-8888}:8888"
    volumes:
      - "${TP_DATA:-/tpdata}/trojan-panel-ui/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${TP_DATA:-/tpdata}/cert/:/tpdata/cert/"
    depends_on:
      - trojan-panel

  trojan-panel-core:
    image: jonssonyan/trojan-panel-core
    container_name: trojan-panel-core
    restart: always
    ports:
      - "${CORE_PORT:-8082}:8082"
      - "${GRPC_PORT:-8100}:8100"
    volumes:
      - "${TP_DATA:-/tpdata}/trojan-panel-core/bin/xray/config/:/tpdata/trojan-panel-core/bin/xray/config/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/bin/trojango/config/:/tpdata/trojan-panel-core/bin/trojango/config/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/bin/hysteria/config/:/tpdata/trojan-panel-core/bin/hysteria/config/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/bin/naiveproxy/config/:/tpdata/trojan-panel-core/bin/naiveproxy/config/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/bin/hysteria2/config/:/tpdata/trojan-panel-core/bin/hysteria2/config/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/logs/:/tpdata/trojan-panel-core/logs/"
      - "${TP_DATA:-/tpdata}/trojan-panel-core/config/:/tpdata/trojan-panel-core/config/"
      - "${TP_DATA:-/tpdata}/cert/:/tpdata/cert/"
      - "${TP_DATA:-/tpdata}/web/:/tpdata/web/"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=trojan-panel-mariadb"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${MARIADB_PASSWORD:-changeme}"
      - "database=trojan_panel_db"
      - "account-table=account"
      - "redis_host=trojan-panel-redis"
      - "redis_port=6378"
      - "redis_pass=${REDIS_PASSWORD:-changeme}"
      - "crt_path=/tpdata/cert/${DOMAIN:-example.com}.crt"
      - "key_path=/tpdata/cert/${DOMAIN:-example.com}.key"
      - "grpc_port=8100"
      - "server_port=8082"
    depends_on:
      - trojan-panel-mariadb
      - trojan-panel-redis
      - trojan-panel